# 데이터 전처리. 
## Label 인코딩, 원-핫 인코딩 (+ PD의 get_dummies API), 

In [1]:
# 1) 레이블 인코딩.    문자열 카테고리명을 1,2,3 등으로 변환.   01,02도 문자열이므로 1,2 로 변환시키는게 맞다.

from sklearn.preprocessing import LabelEncoder

items =['TV', '냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행.
encoder = LabelEncoder()
encoder.fit(items) # 변경할 문자열
labels = encoder.transform(items)  # 위에서 지정한 문자열을 변경시킨다.
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [2]:
# 어떤 문자열 값이 어떤 숫자로 변환됐는지 알고 싶으면 LabelEncoder 객체의 classes_ 속성값으로 확인

print('인코딩 클래스:', encoder.classes_)

# 인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
   # -> 순서대로 0, 1 ,2 ,3 ,4 ,5

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [3]:
# 인코딩 된 값을 디코딩 할 수도 있다.

print('디코딩 원본값:', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [13]:
# 2)  원-핫 인코딩

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items =['TV', '냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서'] # 리스트형

# 숫자값으로 변환 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1, 1)
#[[0]
# [1]
# [4]
# [5]
# [3]
# [3]
# [2]
# [2]]

# 원-핫 인코딩 적용.
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

#[[1. 0. 0. 0. 0. 0.]
# [0. 1. 0. 0. 0. 0.]
# [0. 0. 0. 0. 1. 0.]
# [0. 0. 0. 0. 0. 1.]
# [0. 0. 0. 1. 0. 0.]
# [0. 0. 0. 1. 0. 0.]
# [0. 0. 1. 0. 0. 0.]
# [0. 0. 1. 0. 0. 0.]]
#원-핫 인코딩 데이터 차원
# (8, 6)    행,렬
# 변환 된 인코딩 클래스: ['TV' '냉장고' '믹서2' '선풍기2' '전자레인지' '컴퓨터']
print('인코딩 클래스:', encoder.classes_)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


C:\Users\fu\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [14]:
# get_dummies()는 원-핫 인코딩의 API판으로서, 문자열 카테고리 값을 숫자 형으로 변환할 필요 없이 바로 변환 가능

import pandas as pd

df = pd.DataFrame({'items':['TV', '냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0